@startwbs 券売機
* CUI券売機シミュレータ
**[#SkyBlue] 設計書作成
***[#Yellow] ドメインモデル図
***[#Yellow] ユースケース図
***[#Yellow] オブジェクト図
***[#Yellow] アクティビティ図
***[#Yellow] クラス図
***[#Yellow] シーケンス図
***[#Yellow] WBS
***[#Yellow] 依存関係図
**[#SkyBlue] 開発
***[#Yellow] コア機能の作成
**** ユーザー処理
**** 管理画面
**** システム
**[#SkyBlue] テスト
***[#Yellow] テストコード作成
**** システムテスト
**** 動作確認
**** バグ修正
**[#SkyBlue] レビュー
@endwbs